branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"

preset: "conventionalcommits"

releaseRules:
  - type: "feat"
    release: "minor"
  - type: "fix"
    release: "patch"
  - type: "perf"
    release: "patch"
  - type: "revert"
    release: "patch"
  - type: "docs"
    release: "patch"
  - type: "style"
    release: false
  - type: "chore"
    release: false
  - type: "refactor"
    release: "patch"
  - type: "test"
    release: false
  - type: "build"
    release: false
  - type: "ci"
    release: false
  - scope: "no-release"
    release: false

presetConfig:
  types:
    - type: "feat"
      section: "Features"
    - type: "fix"
      section: "Bug Fixes"
    - type: "perf"
      section: "Performance Improvements"
    - type: "revert"
      section: "Reverts"
    - type: "docs"
      section: "Documentation"
    - type: "style"
      section: "Styles"
    - type: "chore"
      section: "Miscellaneous Chores"
      hidden: true
    - type: "refactor"
      section: "Code Refactoring"
    - type: "test"
      section: "Tests"
      hidden: true
    - type: "build"
      section: "Build System"
      hidden: true
    - type: "ci"
      section: "Continuous Integration"
      hidden: true 